### ISSUE TITLE
Clear input value on event

### ISSUE THREAD

**Issue by nikegp** [abec/react-autosuggest-geocoder#8]
Hi, thanks for fixing the source issue. As I understand your component totally takes control over `inputProps.value` so it's impossible to clear it after an item is selected. I.e. a user selects something and the value is still there, I can't clear it. 

Can you please add support for that? Maybe a method to clear input like it's done in https://github.com/ubilabs/react-geosuggest#clear

I added a workaround to control inputProps on a higher level but it's not that convinient

Thanks!

**Comment by abec** [comment]
Seems like a good idea. I won't be able to get to this for about a week. Send a pull request if you can get to it earlier!

**Comment by abec** [comment]
The 0.5.5 release should have this commit.
